blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/UnknownOlympus/oracle/blob/main/README.md
    about: Check the documentation for help and guides
  - name: ðŸ’¬ Discussions
    url: https://github.com/UnknownOlympus/oracle/discussions
    about: Ask questions and discuss ideas with the community
